version: '3.8'

services:
  postgres:
    container_name: postgres-secretalizer
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=ioet
      - POSTGRES_DB=clients
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data