version: '3.9'
services:
  db:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: backend
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    build: frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
