version: '3.9'
services:
  redis:
    image: redis:alpine
    networks:
      - mynetwork
    # ports:
    #   - 6379:6379

  backend:
    build: backend
    environment:
    # used in Dockerfile
      - HOST=0.0.0.0 
      - PORT=5000
    # used in config.py
      - REDIS_HOST=redis
    networks:
      - mynetwork
    # ports:
    #   - "5000:5000"
    depends_on:
      - redis

  frontend:
    build: frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
